[package]
name = "tagref"
version = "1.3.1"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"
description = "Tagref helps you refer to other locations in your codebase."
license = "MIT"
documentation = "https://github.com/stepchowfun/tagref"
homepage = "https://github.com/stepchowfun/tagref"
repository = "https://github.com/stepchowfun/tagref"
readme = "README.md"

[dependencies]
atty = "0.2"
colored = "1"
ignore = "0.4"
regex = "1"

[dependencies.clap]
version = "2"
features = ["wrap_help"]
